name: Ruby Acceptance Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew assemble
      - name: Set up Ruby
        uses: ruby/setup-ruby@359bebbc29cbe6c87da6bc9ea3bc930432750108
        with:
          ruby-version: '2.5.1'
          working-directory: ./http_server_spec
      - name: Bundle Ruby
        working-directory: ./http_server_spec
        run: bundle install
      - name: Run the Java Http Server and shunt it to the background
        run: ./gradlew run &
      - name: Run the Ruby Tests
        working-directory: ./http_server_spec
        run: bundle exec spinach
